### ISSUE TITLE
Should libraries using Observables appear here?

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/awesome-observables#2]
I'm wondering if frameworks/libraries that use Observables extensively (thinking of Cycle.js, Angular 2, ...) should appear here, or if that should be in a new list (awesome-reactive?).

I fear that a separate list would be a bit light in content, and since they are very much connected to observables, they definitely have their place.

**Comment by sindresorhus** [comment]
I initially wanted to keep it purely for things that are adherent to the ES Observable spec, but that's not a lot yet, so maybe it makes sense to include these too, as long as they're clearly marked as such or in an `Alternative implementation` section?

**Comment by jfmengels** [comment]
To me, this list is not all that helpful if it doesn't include where their power shines. And having a separate list would be missing a lot without the tools to play with Observables.

:+1: for a separate section, but maybe a `Libraries` section? As they're not implementation, but consumers of Observables.

**Comment by sindresorhus** [comment]
👍 Wanna do a PR?

**Comment by jfmengels** [comment]
:+1: Will do one tonight ;)
